### PR TITLE
Fixes for #312

### PR DESCRIPTION
**Pull request by korylprince**
This addresses both problems (in separate commits) I bring up in issue #312:

- v0.6.2 doesn't work when just using <script> tag
- remove window.VueMaterial

You can use either or neither, just figured I would do a PR since I reported it.

### CODE REVIEW

**Comment by marcosmoura** [comment]
Hi @korylprince.

I have to decline this. I already commited this change in the master branch (because this is an exception). I will give you the correct credits on this one! Thank you a lot for the help!

**Comment by korylprince** [comment]
No worries. I just saw you committed the fix lol.

Thanks for being quick to respond and fix!

**Comment by marcosmoura** [comment]
@korylprince Would you mind to tell me your personal email?

**Comment by korylprince** [comment]
Sure, it's korylprince AT gmail DOT com.

**Comment by marcosmoura** [comment]
Cool! To not be public I'm deleting it here...

**Pull request closed without merging**
