### PR TITLE
Implement #319

### PR DESCRIPTION
**Pull request by korylprince**
I've played around with different ideas to implement what I wrote about in #319. The idea I chose is actually very simple, but I'm not sure what you'll think about it.

Firstly the idea is to be able to click the main fab in a speed dial when it's open and have it execute an action. Currently this can't work if md-open is click.

My idea is simply to have the speed dial component emit a `click` (or maybe you want to call it something more descriptive like `fab-trigger-click`, but that seems a bit long...) event if the speed dial is open and the fab-trigger is clicked.

You can listen for this event on the speed dial and execute whatever action you want (e.g. go to another route, open a dialog, etc)

What do you think? If you're okay with this I can update the docs with this event if you want.

### CODE REVIEW

**Comment by pablohpsilva** [comment]
I think its a good idea. Wouldn't be also good to have where the user clicked?

**Comment by korylprince** [comment]
@pablohpsilva passing the click event would require modifying the `toggleSpeedDial` signature, so I'll wait on @marcosmoura as to whether we should do that though.

To be clear though, this only fires when the fab-trigger md-button is clicked, so you basically already know where the user clicked...

**Comment by marcosmoura** [comment]
I think that fire another event is better! Instead of @click. This might be confusing, because custom components need the .native modifier.

**Comment by korylprince** [comment]
@marcosmoura , are you okay with renaming the event to `fab-trigger-click`?

**Comment by korylprince** [comment]
@marcosmoura I pushed a second commit to use a custom event, `md-fab-click` (so it will be prefixed.)

If this doesn't work, can we discuss (perhaps on gitter) a solution to #319?

**Comment by marcosmoura** [comment]
I don't know yet. I'm focusing on those bugfixes and then I get back here with an idea, ok?

**Comment by korylprince** [comment]
No worries. I'm running my application from my fork right now. Fixing bugs is much better :)

**Comment by Morgul** [comment]
@korylprince can you rebase your branch?

**Pull request closed without merging**
